### ISSUE TITLE
Update to Bootstrap v4.3.1

### ISSUE THREAD

**Issue by coliff** [JugglerX/hugo-whisper-theme#11]
Would be good to update to latest version of Bootstrap.

**Comment by JugglerX** [comment]
Yeah its pretty easy, just drop the new bootstrap .scss filersin the scss/bootstrap folder and add any new @imports in the style.scss

**Comment by coliff** [comment]
sure thing - was just reporting here in case you wanted to update in your theme so everyone who downloads it benefits from the updates and fixes.

**Comment by JugglerX** [comment]
No problems, I'll update it next time I update this theme, i can't promise it's a priority so don't wait on me.

**Comment by JugglerX** [comment]
Theme has been updated to bootstrap 4.3.1
