### ISSUE TITLE
How to change color of buttons/hamburger/link text

### ISSUE THREAD

**Issue by tmarasco125** [JugglerX/hugo-whisper-theme#13]
Hello!

How can I change the color of the theme's button/hamburger/link elements on my site using this theme? I can't find a spot for it in the config.toml and changing the SCSS files don't seem to render any updates.

Thank you for your help!

**Comment by martijnengler** [comment]
Changing the $primary color in `assets/scss/_bootstrap-variables.scss` worked for me. (But took a lot of looking around to figure that out.)

**Comment by JugglerX** [comment]
Changing the primary color will change the color for the buttons, links and hamburger. They all run off the scss variable $primary which is found in `scss/_bootstrap-variables.scss`

If you are editing the scss files and nothing is updating, make sure you are running the hugo extended version (this is mentioned in the README) - I've found this is the number 1 issue people have with the scss not working.

If you just want to change the hamburger icon color, you can do so in `assets/scss/components/_hamburger.scss`. Likewise buttons can be overridden in `assets/scss/components/_buttons.scss`

Mainly anything to do with styling this theme is done directly in the scss files.
