### ISSUE TITLE
Summary partial should use Hugo's Content Summary feature

### ISSUE THREAD

**Issue by remeika** [JugglerX/hugo-whisper-theme#19]
Whisper's [default summary partial](https://github.com/JugglerX/hugo-whisper-theme/blob/master/layouts/_default/summary.html) should use Hugo's [Content Summary](https://gohugo.io/content-management/summaries/) feature.

Whisper's summary view shows a link to each page in the docs section, as well as a 140 character preview of the page. To get this preview, it manually snips off the first 140 characters of page content:

```
{{ htmlUnescape .Content | plainify | truncate 140 }}
```

Using the builtin Content Summary instead would provide a few useful features for "free":

- Configurable content preview length
- Ability to source summary text from front matter 

I am happy to submit a PR to do this, just curious if there is a reason not to use this feature. 

Cheers!
James

**Comment by JugglerX** [comment]
I don't know why I did it like that 🤷

happy for you to change it.
