### ISSUE TITLE
fail to deploy the theme in netlify

### ISSUE THREAD

**Issue by RMBindexXMU** [JugglerX/hugo-whisper-theme#2]
Do you know what's the possible issue?
Here's the link.
https://unruffled-feynman-74e24f.netlify.com/
Thanks for your contribution and help

**Comment by JugglerX** [comment]
Yes this should have been fixed. See this commit for the code you need to change, or just pull the latest master branch. https://github.com/JugglerX/hugo-whisper-theme/commit/eeab26acd11ff6bbf633ffe6e3209e5c9a9ba89a

**Comment by RMBindexXMU** [comment]
Thanks for your reply. Have a nice day.
