### ISSUE TITLE
Page strucuture with left sidebar

### ISSUE THREAD

**Issue by easybeau** [JugglerX/hugo-whisper-theme#23]
Hi,

Thanks for this beautiful theme !
I would like to add some content in a different section that _docs_ on the left sidebar. I added a page _Test_. I would like that it appears on the left sidebar with the same page size.

![Capture d’écran_2019-12-26_08-39-00](https://user-images.githubusercontent.com/7128391/71464933-71cf4c80-27bb-11ea-959a-c5d3bbb3f781.png)

How can I do that?
Thanks,
Best regards

**Comment by denizCvrl** [comment]
Define main section folders in config.toml:
[params]
mainSections = ["text", "docs"]

**Comment by easybeau** [comment]
Ok thanks, I will do that !!
