### ISSUE TITLE
fail to preview the theme in Rstudio.

### ISSUE THREAD

**Issue by RMBindexXMU** [JugglerX/hugo-whisper-theme#3]
I am a green hand. 
I fork the project and run `blogdown::serve_site()`
But it doesn't work.
I was told
```
Error in site_root(config) : 
  Could not find config.toml / config.yaml under
```
How to preview the theme in Rstudio?

**Comment by JugglerX** [comment]
I'm not really sure what those commands are. This is a Hugo theme. You should be running the command `hugo` and `hugo server` - See the Readme 

I don't know what Rstudio is.

**Comment by RMBindexXMU** [comment]
Thank you. I am working on it.
