### ISSUE TITLE
add `!default` to variables

### ISSUE THREAD

**Issue by RoeeShlomo** [JugglerX/hugo-whisper-theme#30]
in `assets/scss/_bootstrap-variables.scss` the theme sets attributes such as the primary color. 

Please add `!default` to attributes, to allow projects to override these attributes without changing the source code of the theme. For example, use `$primary: #1de9b6 !default;` instead of `$primary: #1de9b6;`

This will allow a project to create a `style.scss` file to override such attributes, like:
```scss
$primary: #31c3e7;
@import '../../themes/hugo-whisper-theme/assets/scss/style';
```

**Comment by JugglerX** [comment]
@RoeeShlomo Thankyou for your contribution but before I accept the PR i just want to understand if this is an better solution. 

`_bootrap-variables.scss` is already overriding the `bootstrap/variables.scss` defaults. So doesn't it make sense already that `!default` is not used?

Another common pattern is to create another seperate file called `variables.scss` - override the `$primary` variable and import that file below the bootstrap imports in `style.scss`

So while I understand what your getting at, it just seems like an alternative to the existing approach and both approaches are valid.

What do you think? Why is your approach preferable?

**Comment by roee88** [comment]
Hi,

The goal is to to allow projects to override these attributes without changing anything in the source code of the theme. If you can help me understand how the current approach allows it then it would be great!

> _bootrap-variables.scss is already overriding the bootstrap/variables.scss defaults. So doesn't it make sense already that !default is not used?

I'm not sure that I understand the suggestion, can you please clarify? The thing is, without `!default` the assignment takes place regardless of what's defined in bootstrap/variables.scss or what I override afterwards. I think what I ask is described in https://medium.com/@bajena3/a-story-about-overriding-scss-variables-and-the-default-keyword-eace1de34631

> Another common pattern is to create another seperate file called variables.scss - override the $primary variable and import that file below the bootstrap imports in style.scss

That requires changing the theme's source code.

**Comment by JugglerX** [comment]
It seems like any changes to the SCSS or the SCSS variables will require changes to the source code? Whether you are modifying the existing _bootstrap-variables.scss or creating your own file with variables seems like a matter of preference and equal amounts of work.

I'm not being ungracious, I appreciate your PR, but I still don't see how this is an improvement, it simply seems like an alternative approach that you prefer?

If your aim is to edit the color scheme without 'modifying the source code' then a clear improvement would be moving the SCSS variables up into the Hugo config.toml and using Hugo Pipes functionality to read them in the SCSS file. Would you be able to modify your PR to support this?

**Comment by roee88** [comment]
I have closed the PR to avoid the wrong assumption that I push towards a specific approach. I really don't. Instead, let me try to rephrase the question:

1. I would like to be able to use the theme as a submodule, or any other method that allows easily fetching changes that you make to the theme. 
2. I would like to change the color scheme

Hugo does allow you to create a file in the folder hierarchy of the website folder, named the same as that file is named in the theme, and it will take it instead (this is what my suggestion used). I will check again if it works for _bootstrap-variables.scss only, maybe I missed something and it does actually work. I will update here. Anyway, thanks for creating this theme, it's great.

**Comment by RoeeShlomo** [comment]
The following works: 

Add to the site folder `assets/scss/_bootstrap-variables.scss` with the following content:
```scss
@import '../../themes/hugo-whisper-theme/assets/scss/bootstrap-variables';
$primary: #31c3e7;  // or any color
$link-color: $primary;
$link-hover-color: lighten($primary, 20%);
```

**Comment by datenzar** [comment]
> The following works:
> 
> Add to the site folder `assets/scss/_bootstrap-variables.scss` with the following content:
> 
> ```css-scss
> @import '../../themes/hugo-whisper-theme/assets/scss/bootstrap-variables';
> $primary: #31c3e7;  // or any color
> $link-color: $primary;
> $link-hover-color: lighten($primary, 20%);
> ```

That was really helpful as an answer! I was also looking for a way to customize the theme. As a suggestion to @JugglerX, this could be added to the theme documentation.
